错误/异常处理
第一种：SyntaxError：语法错误(犯的错误：单词拼写错误等)
第二种：ReferenceError：引用错误(引用某些变量或者对象的时候找不到)
第三种：TypeError：类型错误(错误的使用了类对象的方法的时候：方法写错了)
第四种：RangeError：范围错误
第五种：EvalError：调用Eval函数的时候出错了
第六种：URLError：调用URL时发生的错误
前四个更重要
错误处理：在程序发生错误的时候保证程序不退出，或者正常退出，该保存的地方保存
如何错误处理：try Catch块 由三部分组成
            try{
                可能出现错误的代码(只有出错的才能放在这里)
            }catch(参数变量err){
                只有发生错误的时候才会执行，一旦发生错误err变量中就会自动存入ERROR对象
                catch一般写的内容：//1.记录/显示错误信息
               8                   //2.继续向调用者抛出异常       
            }finally{
                只要写了就会被执行，可以省略
                //一般情况下释放资源
            }
何时需要定义错误处理呢？
    未知的错误放在try catch块中，已知的错误使用 if   else 结构